import = [
    "~/.config/alacritty/themes/colors.toml",
    "~/.config/alacritty/font.toml",
    "~/.config/alacritty/window.toml",
    "~/.config/alacritty/local.toml",
]

[cursor.style]
blinking = "On"
