[general]
import = [
    "~/.config/alacritty/themes/colors.toml",
    "~/.config/alacritty/font.toml",
    "~/.config/alacritty/window.toml",
    "~/.config/alacritty/local.toml", # optional
]

[cursor.style]
blinking = "On"

[env]
TERM = "xterm-256color"
