[font]
size = {{alacritty_font_size}}

[font.bold]
family = "{{alacritty_font}}"
style = "Bold"

[font.bold_italic]
family = "{{alacritty_font}}"
style = "Bold Italic"

[font.italic]
family = "{{alacritty_font}}"
style = "Italic"

[font.normal]
family = "{{alacritty_font}}"
style = "Regular"
