"$schema" = 'https://starship.rs/config-schema.json'

# https://starship.rs/config/#prompt
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$line_break\
$shell\
$character"""

[character]
success_symbol = '[:](bold 0)'
error_symbol = '[:](bold 9)'
# {{#if (eq zsh_vi 1)}}
# success_symbol = '[I](bold fg:#64a7fc bg:#1f2f44)'
# error_symbol = '[I](bold fg:#f3a6c4 bg:#3a2b30)'
vimcmd_symbol = '[N](bold fg:#64a7fc bg:#1f2f44)'
vimcmd_visual_symbol = '[V](bold fg:#64a7fc bg:#1f2f44)'
vimcmd_replace_one_symbol = '[R](bold fg:#f28674 bg:#3a2829)'
vimcmd_replace_symbol = '[R](bold fg:#f28674 bg:#3a2829)'
# {{/if}}

[cmd_duration]
min_time = 1_500
format = '[$duration]($style) '
# {{#if (eq dark_mode 1)}}
style = 'bold 216'
# {{else}}
style = 'bold 180'
# {{/if}}

[conda]
# {{#if (eq use_nerdfont 1)}}
symbol = "🅒 "
# {{else}}
symbol = "@"
# {{/if}}
style = 'bold 81'
format = '$symbol[$environment]($style) '
ignore_base = false

[directory]
# {{#if (eq use_nerdfont 1)}}
format = "[](bold 7) [$path]($style)[$read_only]($read_only_style) "
# {{else}}
format = "[$path]($style)[$read_only]($read_only_style) "
# {{/if}}
# {{#if (eq dark_mode 1)}}
style = 'bold 15'
# {{else}}
style = 'bold 0'
# {{/if}}

[env_var.CUDA_VISIBLE_DEVICES]
style = 'bold 2'
format = '[N](bold)[v](bold 8)[$env_value]($style) '

[env_var.http_proxy]
format = '[P](bold)[@](bold 8)[http](bold 14) '

[env_var.https_proxy]
format = '[P](bold)[@](bold 8)[https](bold 14) '

[env_var.all_proxy]
format = '[P](bold)[@](bold 8)[all](bold 14) '

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
# {{#if (eq use_nerdfont 1)}}
symbol = ' '
# {{else}}
symbol = ' '
# {{/if}}
style = 'bold 13'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = 'bold 5'

[hostname]
ssh_symbol = ''
format = '[$ssh_symbol$hostname]($style) [in](bold) '
style = 'bold 6'

[package]
# format = '[is](bold) [$symbol$version]($style) '
format = '[$symbol$version]($style) '
# {{#if (eq use_nerdfont 1)}}
symbol = ' '
# {{else}}
symbol = 'p@'
# {{/if}}
style = 'bold 11'

[status]
format = '[$symbol$status]($style) '
# {{#if (eq use_nerdfont 1)}}
symbol = ' '
# {{else}}
symbol = 'c'
# {{/if}}
style = 'bold 9'
disabled = false

[time]
format = '[$time]($style) '
# {{#if (eq dark_mode 1)}}
style = 'bold 0'
# {{else}}
style = 'bold 8'
# {{/if}}
disabled = false

[username]
format = '[$user]($style) [au](bold) '
style_user = 'bold 3'
style_root = 'bold 1'

# disabled packages
[container]
disabled = true
[docker_context]
format = '[$symbol$context]($style) '
symbol = '🐋'
style = 'bold 12'
disabled = true
[deno]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true
[ruby]
disabled = true
[rust]
disabled = true
