{{#if (eq zsh_plugin_fzf_history_search_preview 1)}}
ZSH_FZF_HISTORY_SEARCH_FZF_ARGS='+s +m -x -e'
ZSH_FZF_HISTORY_SEARCH_FZF_EXTRA_ARGS='--preview-window=down:30%'
{{/if}}
ZSH_FZF_HISTORY_SEARCH_END_OF_LINE=1
ZSH_FZF_HISTORY_SEARCH_EVENT_NUMBERS=0
ZSH_FZF_HISTORY_SEARCH_DATES_IN_SEARCH=0
ZSH_FZF_HISTORY_SEARCH_REMOVE_DUPLICATES=1
