#ZSH_HISTORY_FUZZY_SEARCH_BIND=
#ZSH_HISTORY_FUZZY_SEARCH_SHOW_DATES=
#ZSH_HISTORY_FUZZY_SEARCH_SHOW_EVENT_NUMBERS=
#ZSH_HISTORY_FUZZY_SEARCH_FUZZER=
#ZSH_HISTORY_FUZZY_SEARCH_FUZZER_ARGS=
ZSH_HISTORY_FUZZY_SEARCH_REMOVE_DUPLICATES=1
#ZSH_HISTORY_FUZZY_SEARCH_PREVIEW_PIPE_CMD=
if [ -x "$(command -v nvimpager)" ]; then
    ZSH_HISTORY_FUZZY_SEARCH_PREVIEW_PIPE_CMD="nvimpager -c -- -c 'set ft=sh'"
fi
#ZSH_HISTORY_FUZZY_SEARCH_PREVIEW_WINDOW_ARGS=
