{{#if (eq zsh_theme "spaceship")}}
SPACESHIP_PROMPT_ORDER=(
    user
    host
    dir
    conda
    git
    package
    exec_time
    exit_code
    time
    line_sep
    jobs
    char
)

# https://spaceship-prompt.sh/config/prompt/?h=async#options
SPACESHIP_PROMPT_ASYNC=true

# Char
SPACESHIP_CHAR_SYMBOL=': '
SPACESHIP_CHAR_SYMBOL_ROOT='$ '
SPACESHIP_CHAR_SYMBOL_SUCCESS=$SPACESHIP_CHAR_SYMBOL
SPACESHIP_CHAR_SYMBOL_FAILURE=$SPACESHIP_CHAR_SYMBOL
SPACESHIP_CHAR_SYMBOL_SECONDARY=$SPACESHIP_CHAR_SYMBOL
SPACESHIP_CHAR_COLOR_SUCCESS='0'
SPACESHIP_CHAR_COLOR_FAILURE='9'
SPACESHIP_CHAR_COLOR_SECONDARY='11'

# User
SPACESHIP_USER_SHOW='true'
SPACESHIP_USER_COLOR='3'
SPACESHIP_USER_COLOR_SSH='3'

# Hostname
SPACESHIP_HOST_SHOW='true'
SPACESHIP_HOST_SHOW_FULL='false'
SPACESHIP_HOST_PREFIX='au '
# SPACESHIP_HOST_SUFFIX=
SPACESHIP_HOST_COLOR='6'
SPACESHIP_HOST_COLOR_SSH='6'

# Directory
SPACESHIP_DIR_SHOW='true'
{{#if (eq use_nerdfont 1)}}
SPACESHIP_DIR_PREFIX=' '
SPACESHIP_DIR_LOCK_SYMBOL=''
{{else}}
SPACESHIP_DIR_PREFIX='in '
SPACESHIP_DIR_LOCK_SYMBOL='L'
{{/if}}
SPACESHIP_DIR_COLOR='15'

# Git
SPACESHIP_GIT_SHOW='true'
{{#if (eq use_nerdfont 1)}}
SPACESHIP_GIT_PREFIX=' '
SPACESHIP_GIT_SYMBOL=''
{{else}}
SPACESHIP_GIT_PREFIX='au '
{{/if}}
SPACESHIP_GIT_BRANCH_PREFIX=$SPACESHIP_GIT_SYMBOL
SPACESHIP_GIT_BRANCH_SHOW='true'
SPACESHIP_GIT_BRANCH_COLOR='182'
SPACESHIP_GIT_STATUS_SHOW='true'
SPACESHIP_GIT_STATUS_PREFIX=' '
SPACESHIP_GIT_STATUS_SUFFIX=''
SPACESHIP_GIT_STATUS_COLOR='183'
SPACESHIP_GIT_STATUS_UNTRACKED='?'
SPACESHIP_GIT_STATUS_ADDED='+'
SPACESHIP_GIT_STATUS_MODIFIED='!'
SPACESHIP_GIT_STATUS_RENAMEDE='»'
SPACESHIP_GIT_STATUS_DELETED='✘'
SPACESHIP_GIT_STATUS_STASHED='$'
SPACESHIP_GIT_STATUS_UNMERGED='='
SPACESHIP_GIT_STATUS_AHEAD='⇡'
SPACESHIP_GIT_STATUS_BEHIND='⇣'
SPACESHIP_GIT_STATUS_DIVERGED='⇕'

# Package
SPACESHIP_PACKAGE_PREFIX=''
SPACESHIP_PACKAGE_SYMBOL=''
SPACESHIP_PACKAGE_COLOR='115'

# Time
SPACESHIP_TIME_SHOW='true'
SPACESHIP_TIME_PREFIX=''
SPACESHIP_TIME_SUFFIX=' '
SPACESHIP_TIME_FORMAT='%*'
SPACESHIP_TIME_COLOR='0'

# Conda Virtualenv
SPACESHIP_CONDA_SHOW='true'
SPACESHIP_CONDA_PREFIX='@'
SPACESHIP_CONDA_SUFFIX=' '
SPACESHIP_CONDA_SYMBOL=''
SPACESHIP_CONDA_COLOR='81'
SPACESHIP_CONDA_VERBOSE='true'

# Execution time
SPACESHIP_EXEC_TIME_PREFIX=''
SPACESHIP_EXEC_TIME_COLOR='216'

# Exit Code
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_COLOR=9
{{#if (eq use_nerdfont 1)}}
SPACESHIP_EXIT_CODE_SYMBOL=' '
{{else}}
SPACESHIP_EXIT_CODE_SYMBOL='c'
{{/if}}

# Tmux
if [ -z "$TMUX" ] && [ -z "$ZELLIJ" ] && [ ! "$TERM_PROGRAM" = "vscode" ]; then
    SPACESHIP_USER_SHOW='true'
    SPACESHIP_HOST_SHOW='true'
else
    SPACESHIP_USER_SHOW='false'
    SPACESHIP_HOST_SHOW='false'
fi
{{/if}}
