#!/usr/bin/env sh

icon=
icon_fg='#{f_cmd_fg}'
icon_bg='#{f_cmd_bg}'
name=$1

if [ $1 = ash ]; then
    icon=""
fi 
if [ $1 = bash ]; then
    icon=""
fi
if [ $1 = docker ]; then
    icon=""
fi
if [ $1 = git ]; then
    icon=""
fi
if [ $1 = node ]; then
    icon="" # ?
fi
if [ $1 = nvim ]; then
    icon=""
    name="neovim"
fi
if [ $1 = python ] || [ $1 = Python ]; then
    icon=""
    icon_fg="#ffbc03"
    name="python"
fi
if [ $1 = ruby ]; then
    icon=""
fi
if [ $1 = rust ]; then
    icon=""
fi
if [ $1 = ssh ]; then
    icon=""
fi
if [ $1 = sudo ]; then
    icon=""
fi
if [ $1 = tsc ]; then
    # icon=""
    icon="ﯤ"
fi
if [ $1 = vim ]; then
    icon=""
fi
if [ $1 = zsh ]; then
    icon=""
fi

if [ ! -z "$icon" ]; then
    icon="#[fg=$icon_fg,bg=$icon_bg] $icon "
else
    icon=' '
fi
name="#[fg=#{f_cmd_fg},bg=#{f_cmd_bg}]$name "

echo "\
#{default_style}\
$icon\
#{default_style}\
$name"
