#!/usr/bin/env sh

icon=
icon_fg='#{f_cmd_fg}'
icon_bg='#{f_cmd_bg}'
name="$(echo "$1" | tr '[:upper:]' '[:lower:]')"

if [ "$name" = 'ash' ]; then
    icon=""
elif [ "$name" = 'bash' ]; then
    icon=""
elif [ "$name" = 'docker' ]; then
    icon=""
elif [ "$name" = 'git' ]; then
    icon=""
elif [ "$name" = 'node' ]; then
    icon="" # ?
elif [ "$name" = 'nvim' ]; then
    icon=""
    name="neovim"
elif [ "$name" = 'python' ]; then
    icon=""
    icon_fg="#ffbc03"
    name="python"
elif [ "$name" = 'ruby' ]; then
    icon=""
elif [ "$name" = 'rust' ]; then
    icon=""
elif [ "$name" = 'ssh' ]; then
    icon=""
elif ["$name" = 'sudo' ]; then
    icon=""
elif [ "$name" = 'tsc' ]; then
    # icon=""
    icon="ﯤ"
elif [ "$name" = 'vim' ]; then
    icon=""
elif [ "$name" = 'zsh' ]; then
    icon=""
fi

if [ ! -z "$icon" ]; then
    icon="#[fg=$icon_fg,bg=$icon_bg] $icon "
else
    icon=' '
fi
name="#[fg=#{f_cmd_fg},bg=#{f_cmd_bg}]$name "

echo "\
#{default_style}\
$icon\
#{default_style}\
$name"
