#!/usr/bin/env zsh

zparseopts -E -D -a args -realpath+::

_ls() {
    if [ -x "$(command -v exa)" ]; then
        exa -a --color=always --grid $realpath
    else
        ls -a --color=always $realpath
    fi
}

_cat() {
    PREVIEW_SIZE=20000 # preview size in bytes

    filename=$(basename $realpath)
    tmp_fp=/tmp/preview-z-$filename
    head -c $PREVIEW_SIZE $realpath > $tmp_fp
    if [ -x "$(command -v nvimpager)" ]; then
        nvimpager -c $tmp_fp
    elif [ -x "$(command -v bat)" ]; then
        bat -p --color=always --theme=base16 $tmp_fp
    else
        cat $tmp_fp
    fi
    rm $tmp_fp
}

if [[ ! -e $realpath ]]; then
    exit 0
fi

if [[ -d $realpath ]]; then
    _ls
    exit 0
fi

if [[ -f $realpath ]]; then
    if [ -x "$(command -v file)" ]; then
        mime=$(file -ibL $realpath)
        category=${mime%%/*}
        subtype=${mime##*/}; subtype=${subtype%%;*}
        charset=${mime##*charset=}

        if [[ "$category" == 'text' && "$charset" != 'binary' ]]; then
            _cat
        else
            echo $mime
        fi
    else
        _cat
    fi
fi
