# https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration

[scripts.files]
scripts = "~/.scripts"

[git.files]
gitconfig = "~/.gitconfig"

# [git.variables]
# git_email =
# git_username =
# git_signing_key =

[tmux]
depends = ["scripts"]

[tmux.files]
"tmux.conf" = "~/.tmux.conf"

[tmux.variables]
tmux_float = 1
tmux_prefix = "C-b"
tmux_using_plugins = 0

[shell]
depends = ["scripts", "tmux", "git"]

[shell.files]
aliases = "~/.aliases"
hushlogin = "~/.hushlogin"
opener = "~/.opener"

[shell.variables]
shell_nerdfont = 0

[zsh]
depends = ["shell"]

[zsh.files]
"zshrc" = "~/.zshrc"
zsh = "~/.zsh"

[zsh.variables]
zsh_theme = "spaceship"
zsh_plugin_fsh_theme = "~/.zsh/plugins/configs/fsh_jasminetea.ini"
zsh_plugin_fzf_history_search_preview = 0
