# https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration

[global.variables]
use_nerdfont = 0

[scripts.files]
scripts = "~/.scripts"

[git.files]
gitconfig = "~/.gitconfig"

[git.variables]
git_email = ""
git_username = ""
git_signing_key = ""

[tmux]
depends = ["scripts"]

[tmux.files]
"tmux.conf" = "~/.tmux.conf"

[tmux.variables]
tmux_float = 1
tmux_prefix = "C-b"
tmux_using_plugins = 0

[shell]
depends = ["scripts"]

[shell.files]
aliases = "~/.aliases"
hushlogin = "~/.hushlogin"
"env.sh" = "~/.env.sh"
starship = "~/.config/starship"

[zsh]
depends = ["shell"]

[zsh.files]
"zshrc" = "~/.zshrc"
zsh = "~/.zsh"

[zsh.variables]
zsh_theme = "starship"
zsh_plugin_fsh_theme = "~/.zsh/plugins/configs/fsh_jasminetea.ini"
zsh_plugin_fzf_history_search_preview = 0

[nvim.files]
nvim = "~/.config/nvim"

[nvim.variables]
nvim_background = 'dark'           # using light colorscheme
nvim_transparent_bg = 0
nvim_node_host_prog = ""           # rqeuired by coc.nvim; `lib/node_modules/neovim/bin/cli.js`
nvim_python3_host_prog = ""        # required by semshi; `bin/python3`
nvim_plugin_copilot_node_host = "" # required by copilot; `bin/node`
