# https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration

[global.variables]
use_nerdfont = 0

[scripts.files]
scripts = "~/.scripts"

# PACKAGES

[alacritty]
depends = ["global"]

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[conda]
depends = ["global"]

[conda.files]
condarc = "~/.condarc"

[git.files]
gitconfig = "~/.gitconfig"

[git.variables]
git_email = ""
git_username = ""
git_signing_key = ""

[nvim]
depends = ["global"]

[nvim.files]
nvim = "~/.config/nvim"

[nvim.variables]
nvim_background = 'dark'               # using light colorscheme
nvim_transparent_bg = 0
nvim_node_host_prog = ""               # rqeuired by coc.nvim; `lib/node_modules/neovim/bin/cli.js`
nvim_plugin_copilot_node_host = ""     # required by copilot; `bin/node`
nvim_coc_config_home = "~/.config/coc" # h: g:coc_config_home

[nvimpager]
depends = ["nvim"]

[nvimpager.files]
"nvimpager" = "~/.config/nvimpager"

[shell]
depends = ["global", "scripts"]

[shell.files]
aliases = "~/.aliases"
hushlogin = "~/.hushlogin"
"env.sh" = "~/.env.sh"
starship = "~/.config/starship"

[tmux]
depends = ["global", "scripts"]

[tmux.files]
"tmux.conf" = "~/.tmux.conf"

[tmux.variables]
tmux_prefix = "C-b"
tmux_using_plugins = 0

[zsh]
depends = ["shell"]

[zsh.files]
"zshrc" = "~/.zshrc.dot"
zsh = "~/.zsh"

[zsh.variables]
zsh_theme = "starship"
zsh_plugin_autosuggestions = 0
zsh_plugin_fsh_theme = "~/.zsh/plugins/configs/fsh_jasminetea.ini"
zsh_vi = 0
