# https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration

[global.variables]
dark_mode = 1
use_nerdfont = 0

[scripts.files]
scripts = "~/.scripts"

# PACKAGES

[alacritty]
depends = ["global"]

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[alacritty.variables]
alacritty_blur = 0
alacritty_decorations = "Full"
alacritty_font = "RobotoMono Nerd Font"
alacritty_font_size = 14
alacritty_opacity = 0.9
# alacritty_theme = # check available themes in `alacrity/themes`
alacritty_theme_dark = "jasminetea" # only apply when alacritty_theme unset
alacritty_theme_light = "github_light" # only apply when alacritty_theme unset

[conda]
depends = ["global"]

[conda.files]
condarc = "~/.condarc"

[git.files]
gitconfig = "~/.gitconfig"

[git.variables]
git_email = ""
git_username = ""
git_signing_key = ""

[nvim]
depends = ["global"]

[nvim.files]
nvim = "~/.config/nvim"

[nvim.variables]
nvim_transparent_bg = 0

[nvimpager]
depends = ["nvim"]

[nvimpager.files]
"nvimpager" = "~/.config/nvimpager"

[shell]
depends = ["global", "scripts"]

[shell.files]
aliases = "~/.aliases"
hushlogin = "~/.hushlogin"
"env.sh" = "~/.env.sh"
starship = "~/.config/starship"

[tmux]
depends = ["global", "scripts"]

[tmux.files]
"tmux.conf" = "~/.tmux.conf"

[tmux.variables]
tmux_prefix = "C-b"
tmux_theme_color_dark = "simple_red"
tmux_theme_color_light = "simple_purple"
tmux_using_plugins = 0

[yabai.files]
yabai = "~/.config/yabai"

[zsh]
depends = ["shell"]

[zsh.files]
"zshrc" = "~/.zshrc.dot"
zsh = "~/.zsh"

[zsh.variables]
zsh_theme = "starship"
zsh_plugin_autosuggestions = 0
zsh_plugin_fsh_theme_dark = "~/.zsh/plugins/configs/fsh_jasminetea.ini"
zsh_plugin_fsh_theme_light = "~/.zsh/plugins/configs/fsh_github_light.ini"
zsh_vi = 0
